extends: stylelint-config-standard
ignoreFiles:
  - node_modules/**/*

rules:
  alpha-value-notation: number # TODO: fix for `percentage` in tokens
  color-hex-length: long
  color-function-notation: legacy # TODO: fix for `modern` in tokens
  custom-property-pattern: _?[a-z]+[a-z0-9-]*
  declaration-block-no-redundant-longhand-properties: 
    - true
    - ignoreShorthands:
        - /grid/
  indentation: 2
  number-max-precision: 6
  no-descending-specificity:
    - true
    - ignore:
      - selectors-within-list
  selector-class-pattern: null
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-pseudo-element-colon-notation: single
  shorthand-property-no-redundant-values: true
  string-quotes: double
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
      ignoreTypes:
        - heading
        - actions

  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
      - /part(.*)/